alg = {
    1: 'Stack',
    2: 'Queue',
    3: 'List',
    4: 'Sort',
    5: 'Sort_quick',
    6: 'Sort_shell',
    7: 'Sort_Merge',
    8: 'BST',
    9: 'Prim',
    10: 'Dijkstra',
    11: 'Topology',
    12: 'Com_geom',
    13: 'Com_rotate',
}
